// autogenerated
using System.Threading;

#pragma warning disable CS0108 // Member hides inherited member; missing new keyword
namespace KurrentDB.SourceGenerators.Tests.Messaging.ConcreteWithoutGroup
{
	public partial class A
	{
	}
}
